### ISSUE TITLE
undefined method `failure_message_for_should' for class `Class' after upgrading to 0.5.1

### ISSUE THREAD

**Issue by shedd** [tigrish/i18n-spec#12]
I was using version 0.4.1 and I recently upgraded.

My spec is unchanged and still appears to match the example, but now I'm seeing failures like the following:

```
  1) Localization config/locales/en.yml
     Failure/Error: it { expect(have_missing_pluralization_keys).to be false }
     NameError:
       undefined method `failure_message_for_should_not' for class `Class'
     # ./spec/i18n/locales_spec.rb:16:in `block (3 levels) in <top (required)>'

  2) Localization config/locales/en.yml
     Failure/Error: it { should have_valid_pluralization_keys }
     NameError:
       undefined method `failure_message_for_should' for class `Class'
     # ./spec/i18n/locales_spec.rb:15:in `block (3 levels) in <top (required)>'

  3) Localization config/locales/en.yml
     Failure/Error: it { expect(be_parseable).to be true }
     NameError:
       undefined method `failure_message_for_should' for class `Class'
     # ./spec/i18n/locales_spec.rb:14:in `block (3 levels) in <top (required)>'
```

Any ideas?
